version: "3.7"
services:
  app:
    image: amackillop/aio-app
    build: docker/
    expose: 
      - 8000
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 3
  redis:
    image: redislabs/rejson:latest
    expose:
      - "6379"
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8080:80"
