#!/usr/bin/env bash
HOST=${2:-0.0.0.0}
PORT=${3:-$(docker port docker_nginx_1 | cut -d: -f2)}

spam () {
  for ((i=1;i<=$1;i++)); do 
    curl --header "Content-Type: application/json" \
    --request POST \
    --data '{"urls":["https://www.dummyimage.com/80x80", "https://www.dumimage.com/40x40"]}' \
    http://${HOST}:${PORT}/v1/jobs &
    done
  wait
}

time spam $1

