#!/usr/bin/env bash

spam () {
  for ((i=1;i<=$1;i++)); do 
    curl --header "Content-Type: application/json" \
    --request POST \
    --data '{"urls":["https://www.dummyimage.com/80x80", "https://www.dumimage.com/40x40"]}' \
    10.43.79.120:80/v1/images/upload &
    done
  wait
}

time spam $1

