version: "3.7"
services:
  app:
    image: amackillop/aio-app
    expose: 
      - 8000
    environment: 
      - HOST=0.0.0.0
      - PORT=8000
    build: .
    deploy:
      replicas: 10
  redis:
    image: redislabs/rejson:latest
    expose:
      - "6379"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8080:80"
