# apiVersion: v1
# kind: Namespace
# metadata:
#   name: aio-app
#   labels:
#     name: aio-app

---
apiVersion: v1
kind: Service
metadata:
  name: aio-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: aio-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aio-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: aio-app
  replicas: 4
  template:
    metadata:
      labels:
        app: aio-app
    spec:
      containers:
      - name: aio-app
        image: amackillop/aio-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
