# apiVersion: v1
# kind: Namespace
# metadata:
#   name: aio-app
#   labels:
#     name: aio-app

---
apiVersion: v1
kind: Service
metadata:
  name: aio-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: aio-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aio-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: aio-app
  replicas: 1
  template:
    metadata:
      labels:
        app: aio-app
    spec:
      containers:
      - name: aio-app
        image: amackillop/aio-app:latest
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 8000
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redislabs/rejson:latest
        ports:
        - containerPort: 6379
          protocol: TCP
