name: Python application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          make setup-ci
      - name: Lint, Type Check, and Test
        run: |
          make test
      - name: Build Images
        run: |
          make build
      - name: Acceptance
        run: |
          make acceptance
      - name: Push Images
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASS }}"
          make push
